name: dice_generator
description: "Gives Random Dice Output"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assests/dice-images/dice-6.png
  - assests/dice-images/dice-5.png
  - assests/dice-images/dice-4.png
  - assests/dice-images/dice-3.png
  - assests/dice-images/dice-2.png
  - assests/dice-images/dice-1.png
